- name: Setup a Debian minimal install to run as an ITGMania arcade system
  hosts: all
  gather_facts: false
  vars:
    stepmania_release: itgmania-0-9-0
  tasks:
  - name: Create user
    ansible.builtin.user:
      name: stepmania
      comment: game
      password: "{{ stepmania_password| string | password_hash('sha512') }}"

  - name: Create game directory
    ansible.builtin.file:
      path: "{{ stepmania_releases[stepmania_release].dest }}"
      state: directory

  - name: Download StepMania
    ansible.builtin.unarchive:
      src: "{{ stepmania_releases[stepmania_release].url }}"
      remote_src: yes
      dest: "{{ stepmania_releases[stepmania_release].dest }}"
      creates: "{{ stepmania_releases[stepmania_release].binary_path }}"
      extra_opts: "{{ stepmania_releases[stepmania_release].extract_opts }}"
      owner: stepmania
      group: stepmania

  - name: Install dependencies
    ansible.builtin.apt:
      name: "{{ common_dependencies + stepmania_releases[stepmania_release].dependencies }}"
      cache_valid_time: 600

  - name: Create game directory
    ansible.builtin.file:
      path: "{{ stepmania_releases[stepmania_release].dest }}"
      state: directory

  #
  # Tasks to autoboot the game
  #
  - name: Enable lightdm autologin
    ansible.builtin.lineinfile:
       path: /etc/lightdm/lightdm.conf
       regexp: ".*autologin-user\\s*=\\s*($|stepmania)"
       line: "autologin-user = stepmania"

  - name: Force LightDM to restart once SM is closed
    ansible.builtin.lineinfile:
       path: /etc/lightdm/lightdm.conf
       regexp: ".*session-cleanup-script\\s*=\\s*($|pkill)"
       line: "session-cleanup-script = pkill -P1 -fx /usr/sbin/lightdm"

  - name: Disable mouse cursor in X
    ansible.builtin.lineinfile:
       path: /etc/lightdm/lightdm.conf
       regexp: "(^|#)xserver-command\\s*=\\s*"
       line: "xserver-command = X -nocursor"

  - name: Use StepMania as X session
    ansible.builtin.copy:
       dest: /home/stepmania/.xsession
       owner: stepmania 
       group: stepmania
       mode: '0644'
       content: "nice -n 5 {{ stepmania_releases[stepmania_release].binary_path }}"

  - name: Set GRUB configuration (usbhid - polling rate)
    ansible.builtin.copy:
      src: files/grub.cfg
      dest: /etc/default/grub
      mode: "0644"
      owner: root
      group: root
    register: _grub_config

  - name: Update grub
    ansible.builtin.command: update-grub
    when: _grub_config.changed

  - name: Enable and start Lightdm
    ansible.builtin.service:
      name: lightdm
      state: restarted
      enabled: true
