- name: Setup a Debian minimal install to run as an ITGMania arcade system
  hosts: all
  gather_facts: false
  vars:
    default_game: itgmania-1-3-0
    installed_games:
    - itgmania-1-3-0
  tasks:
  - name: Gather all known systemd services
    ansible.builtin.service_facts:
    tags:
    - network

  - name: Ensure systemd preset directory exists
    ansible.builtin.file:
      path: /etc/systemd/system-preset
      state: directory
      owner: root
      group: root
      mode: "0755"

  - name: Prevent apt-installed packages from auto-enabling systemd units
    ansible.builtin.copy:
      dest: /etc/systemd/system-preset/00-disable-all.conf
      content: |
        disable *
      owner: root
      group: root
      mode: "0644"

  - name: Try to disable most common display managers (In case this is not a fresh minimal install)
    ansible.builtin.systemd:
      name: "{{ item }}"
      enabled: false
      masked: true
    when: item in ansible_facts.services
    with_items:
      - lightdm.service
      - sddm.service
      - gdm.service
      - gdm3.service
      - xdm.service
      - lxdm.service
      - slim.service
    ignore_errors: true

  - name: Create user
    ansible.builtin.user:
      name: stepmania
      comment: stepmania game user
      password: "{{ stepmania_password| string | password_hash('sha512') }}"
      groups: 
      - input
      - netdev
      append: yes
      shell: "/usr/bin/bash"
    tags: user

  - name: Create game directory
    ansible.builtin.file:
      path: "{{ game_releases[item].dest }}"
      state: directory
      owner: stepmania
      group: stepmania
    tags: download
    with_items: "{{ installed_games }}"

  - name: Detect architecture
    ansible.builtin.command: uname -m
    register: arch_result
    changed_when: false
    when: arch is not defined

  - name: Select architecture
    ansible.builtin.set_fact:
      arch: "{{ arch_map[arch_result.stdout] | default('x86_64') }}"
    vars:
      arch_map:
        x86_64: x86_64
        amd64: x86_64
        aarch64: arm64
        arm64: arm64
        riscv64: riscv64
    when: arch is not defined

  - name: Download game
    ansible.builtin.unarchive:
      src: "{{ game_releases[item].url[arch] }}"
      remote_src: yes
      dest: "{{ game_releases[item].dest }}"
      creates: "{{ game_releases[item].binary_path }}"
      extra_opts: "{{ game_releases[item].extract_opts }}"
      owner: stepmania
      group: stepmania
    tags: download
    with_items: "{{ installed_games }}"

  - name: Ensure portable.txt does not exist
    ansible.builtin.file:
      path: "{{ game_releases[item].dest }}/portable.txt"
      state: absent
    tags: download
    with_items: "{{ installed_games }}"

  # All the addons (audio device picker) will set configurations
  # for all the supported games
  - name: Ensure game config and song directories exist
    ansible.builtin.file:
      path: "/home/stepmania/{{ item }}"
      state: directory
      owner: stepmania
      group: stepmania
    tags: download
    with_items:
    - ".itgmania/Save"
    - ".local/share/deadsync"
    - "songs"

  - name: Set sound drivers to ALSA-sw - SM games based only
    ansible.builtin.ini_file:
      path: "{{ game_releases[item].config_file }}"
      section: Options
      option: SoundDrivers
      value: "ALSA-sw,Null"
      owner: stepmania
      group: stepmania
      mode: '0644'
      create: true
      backup: true
      no_extra_spaces: true
    with_items: "{{ installed_games }}"
    tags:
    - sound

  - name: Ensure AdditionalSongFoldersReadOnly is set in itgmania Preferences.ini
    ansible.builtin.ini_file:
      path: "{{ game_releases[item].config_file }}"
      section: Options
      option: AdditionalSongFoldersReadOnly
      value: "{{ pack_folder }}"
      owner: stepmania
      group: stepmania
      mode: '0644'
      create: true
      backup: true
      no_extra_spaces: true
    with_items: "{{ installed_games }}"

  - name: Install dependencies
    ansible.builtin.apt:
      name: "{{ common_dependencies + game_releases[item].dependencies }}"
      cache_valid_time: 600
    with_items: "{{ installed_games }}"

  - name: Create file that defines which game will be executed
    ansible.builtin.copy:
       dest: /home/stepmania/run_game.sh
       owner: stepmania 
       group: stepmania
       mode: '0644'
       content: "{{ game_releases[default_game].binary_path }}"

  - name: Check if update-grub is available
    ansible.builtin.stat:
      path: /usr/sbin/update-grub
    register: _update_grub_bin
    tags: grub

  - name: Set GRUB configuration (usbhid - polling rate)
    ansible.builtin.copy:
      src: files/grub.cfg
      dest: /etc/default/grub
      mode: "0644"
      owner: root
      group: root
    register: _grub_config
    when: _update_grub_bin.stat.exists
    tags: grub

  - name: Update grub
    ansible.builtin.command: update-grub
    when: _grub_config.changed
    tags: grub

#
# Install tty_settings and tty_desktop
#
  - name: Install extra system dependencies
    ansible.builtin.apt:
      name: "{{ extra_packages }}"
      cache_valid_time: 600
      install_recommends: no

  # Upload tty run scripts
  - name: tty-all - Upload ttyX-name.sh scripts
    ansible.builtin.copy:
      src: "files/{{ item }}"
      dest: /usr/local/bin/
      owner: root
      group: root
      mode: '0755'
    with_items:
    - tty-switch.sh
    - tty_settings/tty1-game.sh
    - tty_settings/tty2-firefox.sh
    - tty_settings/tty3-desktop.sh
    tags: tty

  # Upload systemd units
  - name: tty-all - Upload ttyX-name.sh scripts
    ansible.builtin.copy:
      src: "files/{{ item }}"
      dest: /etc/systemd/system/
      owner: root
      group: root
      mode: '0644'
    with_items:
    - tty-watch.path
    - tty-watch.service
    - tty_settings/game.service
    - tty_settings/settings.service
    - tty_settings/desktop.service
    tags: tty

  # Upload greetd config
  - name: tty3 - Upload greetd config.toml
    ansible.builtin.copy:
      src: files/greetd_config.toml
      dest: /etc/greetd/config.toml
      owner: root
      group: root
      mode: '0644'
    tags: tty

  - name: tty2-settings - Create firefox profile directory
    ansible.builtin.file:
      path: "/home/stepmania/.settings_firefox_profile"
      state: directory
      owner: stepmania
      group: stepmania
    tags: tty

  - name: tty2-settings - Configure firefox to not start in safe mode
    ansible.builtin.file:
      path: "/home/stepmania/.settings_firefox_profile"
      state: directory
      owner: stepmania
      group: stepmania
    tags: tty

  - name: Copy firefox settings tty configuration
    ansible.builtin.copy:
      src: tty_settings/firefox_user.js
      dest: /home/stepmania/.settings_firefox_profile/user.js
      owner: stepmania
      group: stepmania
      mode: '0644'

  - name: Copy JWM config
    ansible.builtin.copy:
      src: files/system.jwmrc
      dest: /etc/jwm/system.jwmrc
      owner: root
      group: root
      mode: '0644'
    tags: tty

  - name: ensure firefox policies directory exists
    ansible.builtin.file:
      path: /etc/firefox/policies
      state: directory
      owner: root
      group: root
      mode: '0755'
    tags: tty

  - name: create firefox profile
    ansible.builtin.copy:
      src: files/tty_settings/policies.json
      dest: /etc/firefox/policies/policies.json
      owner: root
      group: root
      mode: '0644'
    tags: tty

  - name: Ensure greetd is disabled
    ansible.builtin.systemd:
      name: greetd.service
      masked: true
      enabled: false
    tags: tty

  - name: Upload cockpit plugins
    ansible.builtin.copy:
      src: "files/cockpit_modules/{{ item }}"
      dest: /usr/share/cockpit/
      owner: root
      group: root
      mode: preserve
    tags:
    - wifi
    - cockpit
    with_items:
    - select-audio
    - wifi
    - ethernet
    - packman
    - game-manager
    - debian-update
    - input

  - name: DBus rule - allow netdev group to manage wifi
    ansible.builtin.copy:
      src: files/cockpit_modules/net.connman.iwd-netdev.conf
      dest: /etc/dbus-1/system.d/net.connman.iwd-netdev.conf
      mode: "0644"
      owner: root
      group: root
    tags: wifi

  - name: Install CPU governor unit
    ansible.builtin.copy:
      src: misc/cpu-governor.service
      dest: /etc/systemd/system/cpu-governor.service
      owner: root
      group: root
      mode: "0644"
    tags: systemd

  - name: Enable game and required systemd units
    ansible.builtin.systemd:
      name: "{{ item }}"
      enabled: true
    with_items:
    - tty-watch.path
    - cockpit.service
    - game.service
    - cpu-governor.service
    tags:
    - cockpit
    - network
    - systemd

  - name: Add stepmania user to sudoers
    community.general.sudoers:
      name: stepmania
      user: stepmania
      commands: ALL
      nopassword: false
    tags:
    - sudo

  - name: Set passwordless sudo rules for stepmania user - manage game lifecycle
    community.general.sudoers:
      name: stepmania-game-lifecycle
      user: stepmania
      commands:
      - /usr/share/cockpit/select-audio/set_audio_device.sh
      - /usr/bin/systemctl restart game
      - /usr/bin/systemctl start game
      - /usr/bin/systemctl stop game
      nopassword: true
    tags:
      - sudo

  - name: Set default to graphical target
    ansible.builtin.command: "systemctl set-default graphical.target"

  - name: Install sm-packman
    ansible.builtin.include_tasks:
      file: tasks/packman.yaml
      apply:
        tags: packman
    tags:
    - packman

  - name: Check if this is a Raspberry Pi
    ansible.builtin.slurp:
      src: /proc/device-tree/model
    register: _device_model
    ignore_errors: true
    tags:
    - rpi

  - name: Set is_raspberry_pi fact
    ansible.builtin.set_fact:
      is_raspberry_pi: "{{ raspberrypi_build | default(false) | bool or (_device_model is succeeded and 'Raspberry Pi' in (_device_model.content | b64decode)) }}"
    tags:
    - rpi

  - name: Include Raspberry Pi specific tasks
    ansible.builtin.include_tasks: tasks/extra_rpi.yaml
    when: is_raspberry_pi
    tags:
    - rpi

  # Change network stack before rebooting
  - name: Replace network stack
    include_tasks: tasks/network.yaml

  - name: "Reboot system  (Ignore the error)"
    ansible.builtin.command: "/sbin/shutdown -r now"
    async: 0
    poll: 0
    ignore_errors: true
    tags:
    - reboot
    - live
