- name: Setup a Debian minimal install to run as an ITGMania arcade system
  hosts: all
  gather_facts: false
  vars:
    default_game: itgmania-1-3-0
    installed_games:
    - itgmania-1-2-1
    arch: x86_64
  tasks:
  - name: Gather all known systemd services
    ansible.builtin.service_facts:
    tags:
    - network

  - name: Try to disable most common display managers (In case this is not a fresh minimal install)
    ansible.builtin.systemd:
      name: "{{ item }}"
      enabled: false
      state: stopped
    when: item in ansible_facts.services
    with_items:
      - lightdm.service
      - sddm.service
      - gdm.service
      - gdm3.service
      - xdm.service
      - lxdm.service
      - slim.service
    ignore_errors: true

  - name: Create user
    ansible.builtin.user:
      name: stepmania
      comment: stepmania game user
      password: "{{ stepmania_password| string | password_hash('sha512') }}"
      groups: 
      - input
      - netdev
      append: yes
      shell: "/usr/bin/bash"
    tags: user

  - name: Create game directory
    ansible.builtin.file:
      path: "{{ game_releases[item].dest }}"
      state: directory
      owner: stepmania
      group: stepmania
    tags: download
    with_items: "{{ installed_games }}"

  - name: Download game
    ansible.builtin.unarchive:
      src: "{{ game_releases[item].url[arch] }}"
      remote_src: yes
      dest: "{{ game_releases[item].dest }}"
      creates: "{{ game_releases[item].binary_path }}"
      extra_opts: "{{ game_releases[item].extract_opts }}"
      owner: stepmania
      group: stepmania
    tags: download
    with_items: "{{ installed_games }}"

  - name: Ensure portable.txt does not exist
    ansible.builtin.file:
      path: "{{ game_releases[item].dest }}/portable.txt"
      state: absent
    tags: download
    with_items: "{{ installed_games }}"

  # All the addons (audio device picker) will set configurations
  # for all the supported games
  - name: Ensure game config and song directories exist
    ansible.builtin.file:
      path: "/home/stepmania/{{ item }}"
      state: directory
      owner: stepmania
      group: stepmania
    tags: download
    with_items:
    - ".itgmania/Save"
    - ".local/share/deadsync"
    - "songs"

  - name: Ensure AdditionalSongFoldersReadOnly is set in itgmania Preferences.ini
    ansible.builtin.ini_file:
      path: "{{ game_releases[item].config_file }}"
      section: Options
      option: AdditionalSongFoldersReadOnly
      value: /home/stepmania/songs
      owner: stepmania
      group: stepmania
      mode: '0644'
      create: true
      backup: true
      no_extra_spaces: true
    with_items: "{{ installed_games }}"

  - name: Install dependencies
    ansible.builtin.apt:
      name: "{{ common_dependencies + game_releases[item].dependencies }}"
      cache_valid_time: 600
    with_items: "{{ installed_games }}"

  - name: Create file that defines which game will be executed
    ansible.builtin.copy:
       dest: /home/stepmania/run_game.sh
       owner: stepmania 
       group: stepmania
       mode: '0644'
       content: "{{ game_releases[default_game].binary_path }}"

  - name: Set GRUB configuration (usbhid - polling rate)
    ansible.builtin.copy:
      src: files/grub.cfg
      dest: /etc/default/grub
      mode: "0644"
      owner: root
      group: root
    register: _grub_config
    tags: grub

  - name: Update grub
    ansible.builtin.command: update-grub
    when: _grub_config.changed
    tags: grub

#
# Install tty_settings and tty_desktop
#
  - name: Install extra system dependencies
    ansible.builtin.apt:
      name: "{{ extra_packages }}"
      cache_valid_time: 600
      install_recommends: no

  # Upload tty run scripts
  - name: tty-all - Upload ttyX-name.sh scripts
    ansible.builtin.copy:
      src: "files/{{ item }}"
      dest: /usr/local/bin/
      owner: root
      group: root
      mode: '0755'
    with_items:
    - tty-switch.sh
    - tty_settings/tty1-game.sh
    - tty_settings/tty2-firefox.sh
    - tty_settings/tty3-desktop.sh

  # Upload systemd units
  - name: tty-all - Upload ttyX-name.sh scripts
    ansible.builtin.copy:
      src: "files/{{ item }}"
      dest: /etc/systemd/system/
      owner: root
      group: root
      mode: '0644'
    with_items:
    - tty-watch.path
    - tty-watch.service
    - tty_settings/game.service
    - tty_settings/settings.service
    - tty_settings/desktop.service

  # Upload greetd config
  - name: tty3 - Upload greetd config.toml
    ansible.builtin.copy:
      src: files/greetd_config.toml
      dest: /etc/greetd/config.toml
      owner: root
      group: root
      mode: '0644'

  - name: tty2-settings - Create firefox profile directory
    ansible.builtin.file:
      path: "/home/stepmania/.settings-firefox-profile"
      state: directory
      owner: stepmania
      group: stepmania

  - name: Copy JWM config
    ansible.builtin.copy:
      src: files/system.jwmrc
      dest: /etc/jwm/system.jwmrc
      owner: root
      group: root
      mode: '0644'

  - name: ensure firefox policies directory exists
    ansible.builtin.file:
      path: /etc/firefox/policies
      state: directory
      owner: root
      group: root
      mode: '0755'

  - name: create firefox profile
    ansible.builtin.copy:
      src: files/tty_settings/policies.json
      dest: /etc/firefox/policies/policies.json
      owner: root
      group: root
      mode: '0644'

  - name: Ensure greetd is disabled
    ansible.builtin.systemd:
      name: greetd.service
      enabled: false
      state: stopped

  - name: Enable and start game
    ansible.builtin.systemd:
      name: game.service
      enabled: true
      state: started

  - name: Upload iwd cockpit plugins
    ansible.builtin.copy:
      src: "files/cockpit_modules/{{ item }}"
      dest: /usr/share/cockpit/
      owner: root
      group: root
      mode: preserve
    tags:
    - wifi
    - cockpit
    with_items:
    - select-audio
    - wifi
    - ethernet
    - packman
    - select-game

  - name: Set iwd config
    ansible.builtin.ini_file:
      path: /etc/iwd/main.conf
      section: General
      option: EnableNetworkConfiguration
      value: true
      create: false
      backup: false
      no_extra_spaces: true
    tags: wifi

  - name: DBus rule - allow netdev group to manage wifi
    ansible.builtin.copy:
      src: files/cockpit_modules/net.connman.iwd-netdev.conf
      dest: /etc/dbus-1/system.d/net.connman.iwd-netdev.conf
      mode: "0644"
      owner: root
      group: root
    tags: wifi

  - name: Enable and start required systemd units
    ansible.builtin.systemd:
      name: "{{ item }}"
      enabled: true
      state: started
    with_items:
    - tty-watch.path
    - cockpit.service
    - systemd-networkd
    - systemd-resolved
    tags:
    - cockpit
    - network

  - name: Disable network managers
    ansible.builtin.systemd:
      name: "{{ item }}"
      enabled: false
      masked: true
      state: stopped
    when: item in ansible_facts.services
    with_items:
    - networking
    - NetworkManager
    ignore_errors: true
    tags:
    - network 

  - name: Add stepmania user to sudoers
    community.general.sudoers:
      name: stepmania
      user: stepmania
      commands: ALL
      nopassword: false
    tags:
    - sudo

  - name: Restart polkit
    ansible.builtin.systemd:
      name: polkit
      state: restarted
