- name: Disable specified systemd unit
  ansible.builtin.systemd_service:
    state: stopped
    masked: true
    enabled: false
    name: "{{ item }}"
  when: item in ansible_facts.services
  with_items:
  - ModemManager.service
  - bluetooth.service
  - avahi-daemon.service
  - nfs-client.service
  - dphys-swapfile.service
  tags: systemd

- name: Disable swap
  ansible.builtin.lineinfile:
    path: "/etc/dphys-swapfile"
    regexp: "^#?CONF_SWAPSIZE="
    line: "CONF_SWAPSIZE=0"
  tags: swap
  ignore_errors: true

- name: Set /tmp in memory
  ansible.builtin.lineinfile:
    path: "/etc/fstab"
    line: "tmpfs /tmp tmpfs defaults,noatime,nosuid,nodev,size=100M 0 0"
  tags: tmpmem

- name: Set /var/log in memory
  ansible.builtin.lineinfile:
    path: "/etc/fstab"
    line: "tmpfs /var/log tmpfs size=40M 0 0"
  tags: tmplogs

- name: Set journal to maximum 10M of logs
  ansible.builtin.lineinfile:
    path: "/etc/systemd/journald.conf"
    regexp: "^#?SystemMaxUse="
    line: "SystemMaxUse=10M"
  tags: tmplogs

- name: Set journal to log to memory
  ansible.builtin.lineinfile:
    path: "/etc/systemd/journald.conf"
    regexp: "^#?Storage="
    line: "Storage=volatile"
  tags: tmplogs

- name: Gather mount facts
  ansible.builtin.setup:
    gather_subset:
    - mounts

  # https://stackoverflow.com/a/25979548
- name: Set rootfs to noatime
  ansible.builtin.mount:
    name: "{{ item.mount }}"
    src: "{{ item.device }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.options }},noatime"
    state: present
  with_items: "{{ ansible_mounts }}"
  when: item.mount == "/" and item.options.find(",") >= 0 and item.options.find("noatime") == -1

- name: Set rootfs to nodiratime
  ansible.builtin.mount:
    name: "{{ item.mount }}"
    src: "{{ item.device }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.options }},nodiratime"
    state: present
  with_items: "{{ ansible_mounts }}"
  when: item.mount == "/" and item.options.find(",") >= 0 and item.options.find("nodiratime") == -1

- name: Set rootfs to commit=900
  ansible.builtin.mount:
    name: "{{ item.mount }}"
    src: "{{ item.device }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.options }},commit=900"
    state: present
  with_items: "{{ ansible_mounts }}"
  when: item.mount == "/" and item.options.find(",") >= 0 and item.options.find("commit=900") == -1

- name: Create .xsession-errors as a symbolic link to /dev/null
  file:
    state: "link"
    src: "/dev/null"
    force: true
    dest: "/home/stepmania/.xsession-errors"

- name: Disable ITGMania log to file
  ansible.builtin.lineinfile:
    path: "/home/stepmania/.itgmania/Save/Preferences.ini"
    regexp: "^LogToDisk"
    line: "LogToDisk=0"
  tags: tmplogs

- name: Delay page cache writeback to reduce SD card wear
  ansible.builtin.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-sdcard-writeback.conf
    state: present
    reload: true
  with_items:
  - { name: vm.dirty_writeback_centisecs, value: '500' }
  - { name: vm.dirty_expire_centisecs, value: '9000' }
